name: github-actions-test1
on: workflow_dispatch

jobs:
  my_first_job1:
    runs-on: ubuntu-latest
    steps:
      - name: print the greeting message
        run: echo "hello"
      - name: print docker username
        run: echo ${{vars.DOCKER_USERNAME}}
